### 작품 생성하기
POST {{host}}/article
Content-Type: application/json
Authorization: Bearer <your-token>

{
  "title": "category test title",
  "description": "category test",
  "tags": [
    "tag1",
    "tag2"
  ],
  "category": "free"
}

### 작품 리스트 불러오기
GET {{host}}/article

### 작품 상세 불러오기 (쓸 데 없음)
GET {{host}}/article/<article-id>