GET http://localhost:8080/episode/63e1053ab8cf1535b8455ca5?page=0&take=10
Accept: application/json

###
POST http://localhost:8080/episode
Content-Type: application/json
Authorization: Bearer <your-token>

{
  "title": "프롤로그",
  "content": "대충 1화입니다. 뭐 흥미 끌 수 있는 부분으로다가.. ㅖ.. 요새 거,, 너무 길어도 안팔린대 근데 그래서 한국 레전드 프로게이머인 내가,,,",
  "publishedAt": "2023-02-06T14:11:28.037Z",
  "articleId": "someArticleId"
}

###

