### 작품 ID 별로 에피소드 목록 불러오기
GET {{host}}/episode?articleId=<article-id>&page=0&take=10
Accept: application/json

### 에피소드 상세 불러오기
GET {{host}}/episode/<episode-id>
Accept: application/json

### 에피소드 쓰기
POST {{host}}/episode
Content-Type: application/json
Authorization: Bearer <your-token>

{
  "title": "프롤로그",
  "content": "대충 3화입니다. 뭐 흥미 끌 수 있는 부분으로다가.. ㅖ.. 요새 거,, 너무 길어도 안팔린대 근데 그래서 한국 레전드 프로게이머인 내가,,,",
  "publishedAt": "2023-02-16T14:19:49.365Z",
  "articleId": "<article-id>"
}

### 에피소드 수정하기
PATCH {{host}}/episode/<episode-id>
Content-Type: application/json
Authorization: Bearer <your-token>

{
  "episodeId": "<your-episode-id>",
  "title": "프롤로그",
  "content": "대충 3화입니다. 뭐 흥미 끌 수 있는 부분으로다가.. ㅖ.. 요새 거,, 너무 길어도 안팔린대 근데 그래서 한국 레전드 프로게이머인 내가,,,",
  "publishedAt": "2023-02-16T14:19:49.365Z"
}

### 에피소드 좋아요 하기
PUT {{host}}/episode/<article-id>/like
Content-Type: application/json
Authorization: Bearer <your-token>

{
  "like": true
}
